### ISSUE TITLE
 No config file 'alembic.ini' found, or file has no '[alembic]' section

### ISSUE THREAD

**Issue by Podolyan98** [tulir/mautrix-facebook#101]
I am trying to create a database using alembic upgrade head `alembic -x config=/etc/yunohost/apps/matrix-facebook/venv/lib/python3.7/site-packages/mautrix_facebook/config.yaml upgrade head` but I get the error:

`FAILED: No config file 'alembic.ini' found, or file has no '[alembic]' section`

**Comment by tulir** [comment]
You have to run alembic in the directory where alembic.ini is
