### ISSUE TITLE
Invalid macaroon passed

### ISSUE THREAD

**Issue by Podolyan98** [tulir/mautrix-facebook#102]
When I start the bridge I get this stack trace:

> [2020-09-26 06:35:10,726] [INFO@mau.init] Initializing mautrix-facebook 0.1.0rc3
> [2020-09-26 06:35:10,739] [INFO@mau.init] Initialization complete in 0.11 seconds
> [2020-09-26 06:35:10,739] [DEBUG@mau.init] Running startup actions...
> [2020-09-26 06:35:10,739] [DEBUG@mau.init] Starting appservice...
> [2020-09-26 06:35:10,740] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29319
> [2020-09-26 06:35:10,741] [INFO@mau.mx] Ensuring connectivity to homeserver
> [2020-09-26 06:35:10,763] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
> Traceback (most recent call last):
>   File "/etc/yunohost/apps/matrix-facebook/venv/lib/python3.7/site-packages/mautrix/bridge/matrix.py", line 75, in wait_for_connection
>     await self.az.intent.whoami()
>   File "/etc/yunohost/apps/matrix-facebook/venv/lib/python3.7/site-packages/mautrix/client/api/authentication.py", line 32, in whoami
>     resp = await self.api.request(Method.GET, Path.account.whoami)
>   File "/etc/yunohost/apps/matrix-facebook/venv/lib/python3.7/site-packages/mautrix/api/http.py", line 203, in request
>     return await self._send(method, endpoint, content, query_params, headers or {})
>   File "/etc/yunohost/apps/matrix-facebook/venv/lib/python3.7/site-packages/mautrix/api/http.py", line 145, in _send
>     errcode=errcode, message=message)
> mautrix.errors.request.MUnknownToken: Invalid macaroon passed.

homeserver.yaml:
```
app_service_config_files: 
  - /etc/yunohost/apps/facebook/registration.yaml
```

**Comment by shukon** [comment]
Did you restart synapse? (Probably `yunohost service restart matrix-synapse`)

**Comment by Parmeezan** [comment]
> Did you restart synapse? (Probably `yunohost service restart matrix-synapse`)

Oh sure

**Comment by Podolyan98** [comment]
Yes, of course

**Comment by shukon** [comment]
Ok, sorry :D Solved my problems and it was mentioned over at https://github.com/tulir/mautrix-telegram/issues/319 so I figured I'd mention it.

**Comment by sxvghd** [comment]
Are you running the latest release?
I had a similar problem with it, but the code from master runs just fine.

**Comment by Podolyan98** [comment]
I was unable to start the bridge on Yunohost. Reinstalled [Synapse ](https://www.howtoforge.com/tutorial/how-to-install-matrix-synapse-on-ubuntu-20-04/)and it worked this time. Thank you all for your help!
