### ISSUE TITLE
Replies not working

### ISSUE THREAD

**Issue by Dzordzu** [tulir/mautrix-facebook#106]
## Bug description
Simply - replies do not work. They are not visible from the facebook perpective. On the other hand, replies sent from the normal messenger are normally visible. No errors are logged. 

## Current behaviour
![image](https://user-images.githubusercontent.com/17514622/97356138-1b79e100-1898-11eb-9ac2-d1dda36b07a5.png)
![image](https://user-images.githubusercontent.com/17514622/97356147-216fc200-1898-11eb-902b-4d2bc528cd71.png)

## Expected behaviour
Repies are visible on facebook

**Comment by mrjohnson22** [comment]
Replying to yourself also isn't visible on Facebook.

**Comment by Dzordzu** [comment]
I'm happy that @tulir in [this commit](https://github.com/tulir/mautrix-facebook/commit/f150a08d96a2a855937aec16bf77d3e99af433ed) fixed the issue :)
