### ISSUE TITLE
Can't log in: "Got empty response when trying to check login"

### ISSUE THREAD

**Issue by FuzzyMistborn** [tulir/mautrix-facebook#109]
Getting the following error when I try to log in to FB using `login-cookie`.  Has worked fine before.

```

[2020-11-12 14:55:53,425] [ERROR@mau.commands] Failed to log in,
Traceback (most recent call last):,
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/commands/auth.py", line 133, in enter_login_cookies,
    session = await fbchat.Session.from_cookies({,
  File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 582, in from_cookies,
    raise _exception.FacebookError("Got empty response when trying to check login"),
  File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 520, in _from_session,
    return await cls._from_session(session=session, domain=domain),
fbchat.FacebookError: Got empty response when trying to check login
```
Running in Docker, have done a docker pull to make sure I'm on latest image.

**Comment by gwiazdorrr** [comment]
Same. Login-cookie was the only login option that worked for me.

**Comment by rufflepot** [comment]
This just started happening to me the other day. Interestingly enough, I have to containers running for two separate Facebook accounts and only one of them ran into this error.

**Comment by gwiazdorrr** [comment]
This issue lies not in the bridge itself, but in https://github.com/tulir/fbchat-asyncio (same author). It on the other hand is a fork of fbchat, which has been abandoned recently: https://github.com/fbchat-dev/fbchat/issues/613.

**Comment by tulir** [comment]
Cookie login seems to be working fine for me. Are you sure you didn't take cookies from the wrong domain or log out before entering them into the bridge?

**Comment by FuzzyMistborn** [comment]
Yes I'm sure on both. Done the same thing I've done several times.

**Comment by FuzzyMistborn** [comment]
I was just able to login today successfully, so it's a fleeting issue it looks like.

**Comment by rufflepot** [comment]
I succeeded today as well but I tried Chrome instead of Firefox for the first time, so I'm not sure if that was the reason.

**Comment by gwiazdorrr** [comment]
Still no luck for me, no matter the browser.

**Comment by spantaleev** [comment]
The bridge has been stable for me for many months now, with just the occasional `refresh` I had to do.

Since today, I can send messages, but can't receive them. Refreshing also responds with the same message. Here's the full exception:

```
[2020-11-22 08:21:31,582] [ERROR@mau.user.@slavi:devture.com] Failed to restore session
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/mautrix_facebook/user.py", line 231, in load_session
session = await fbchat.Session.from_cookies(self._session_data,
File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 582, in from_cookies
return await cls._from_session(session=session, domain=domain)
File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 520, in _from_session
raise _exception.FacebookError("Got empty response when trying to check login")
fbchat.FacebookError: Got empty response when trying to check login
```

**Comment by spantaleev** [comment]
The bridge has been stable for me for many months now, with just the occasional `refresh` I had to do.

Since today, I can send messages, but can't receive them. Refreshing also responds with the same message. Here's the full exception:

```
[2020-11-22 08:21:31,582] [ERROR@mau.user.@USER:DOMAIN Failed to restore session
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/mautrix_facebook/user.py", line 231, in load_session
session = await fbchat.Session.from_cookies(self._session_data,
File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 582, in from_cookies
return await cls._from_session(session=session, domain=domain)
File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 520, in _from_session
raise _exception.FacebookError("Got empty response when trying to check login")
fbchat.FacebookError: Got empty response when trying to check login
```

**Comment by Sun-volt** [comment]
It was working fine until yesterday. (with `login-cookie` and `login`)

But today I get an identical error "Failed to log in: Got empty response when trying to check login".
I tried all the available methods and different browsers too. 
No difference.

**Comment by christnt** [comment]
Same here since a couple days ( with `login` and `login-cookie` commands).

Message: `Failed to log in: Got empty response when trying to check login` for both.

Sometimes this: `Failed to log in: Failed logging in: https://www.messenger.com/login/checkpoint_interstitial/?next=https%3A%2F%2Fwww.facebook.com%2Fcheckpoint%2Fstart****cookie****step****inst****aid****null****null****.ch.****-rlf_****next%3Dhttps%253A%252F%252Fwww.messenger.com%252F%26hash%3DAWXwrbOUOgm9m-ryEyc, None` for `login` command. _I have replace %hex values by **** for privacy concern_.

Two-Factor Authentication on or off show the same results. Only less a step with it off. 

I have created a brand new Facebook account yesterday for the occasion and successfully logged-in with merely the `login` command. 
When logging-in to my actual FB account, a perpetual "you tried to connect from *my actual* location. Please confirm." step appears. This is not the case with my brand new temporary FB account I successful log-in with the bridge.

May I suggest that _either_ we are locked-out from connecting with the bridge for "security" reason after too many attempts by Facebook _or_ that an extra step is missing in the bridge for this case scenario where access location has to be confirmed.

**Comment by spantaleev** [comment]
Somehow my bridge started working again after restarting it (a few days later). It backfilled some hundreds of messages in various conversations. Interesting..

**Comment by gwiazdorrr** [comment]
Started to work for me too.

**Comment by christnt** [comment]
For me as well.☺

**Comment by christnt** [comment]
The bug is back today 😕. I got disconnected for no reason and I cannot login back again, with neither `login` nor `login-cookie`. I have restarted the bridge.

**Comment by gwiazdorrr** [comment]
Same here.

**Comment by spantaleev** [comment]
If anyone could confirm that the fix from tulir/fbchat-asyncio#28 works for them, that would probably be helpful.

**Comment by christnt** [comment]
I might have done it wrong, but after upgrading the bridge with the latest version from the master branch, nothing changed. I still cannot connect to my FB account. Same error messages; "Failed to log in: Got empty response when trying to check login".

Do I have to apply something in particular to get the fix into my bridge?

What I have done so far:

1. Stopped the bridge;
2. Changed to the bridge folder and activated with `source ./bin/activate`;
3. `pip install --upgrade https://github.com/tulir/mautrix-facebook/tarball/master#egg=mautrix-facebook`;
4. `alembic upgrade head`;
5. Started the bridge.

Is that enough to get the fix or do I need extra commands? Sorry for asking, but I am a noob with that.

**Comment by christnt** [comment]
My very bad.

It works with `login-cookie` and @spantaleev's commit.

@tulir Can you please check the commit? It seems to solve the issue.
