### ISSUE TITLE
Build Docker-image for armv7

### ISSUE THREAD

**Issue by MrAdam** [tulir/mautrix-facebook#110]
Hi there.
I'd like to suggestan update for the Docker-image builder to support armv7 images as well, for running on the Raspberry Pi.

`ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`

**Comment by tulir** [comment]
Raspberry Pi model 2B v1.2 (2016) and later are armv8, you just need to use a 64-bit OS.

**Comment by MrAdam** [comment]
I'm sorry, you're completely right!
I've been running my Raspberry Pi 4B server for so long that it's still on an old 32-bit version.
