### ISSUE TITLE
Partial import of contacts and discussions

### ISSUE THREAD

**Issue by lakano** [tulir/mautrix-facebook#114]
Hello!
I've just installed Synapse and your Messenger bridge, and after login with the bot, I've received about ten requests to discuss, from recent discussions. 
When I've tried to accept them, I had sometimes a « Too many request » error, and needed to wait few seconds to continue. 
I don't known if it's linked to theses errors, but all grouped discussions are partial, there is only 2 or 3 members where some discussions have until 20 members.
I don't known what's the best way to resolve this, may be there is a reset option to restart from scratch ?
Thanks in advance

**Comment by JuniorJPDJ** [comment]
There's a solution to your issue: https://github.com/tulir/mautrix-telegram/issues/536 ;)

**Comment by lakano** [comment]
@JuniorJPDJ I'll try to adjust rc_joins / local / per_second = 10 (10 requests accepted per second) and burst_count = 30 (30 request before being throttled)

But is it possible to auto-accept all rc_joins for the plugin and prevent to manually accept theses requests please ?

**Comment by JuniorJPDJ** [comment]
Those should be auto-accepted if your bridge is using double puppetting (at least most of them).
BTW. Also element has button to accept all pending invites in settings.
