### ISSUE TITLE
Improper parsing of postgres connection string after 0.2 upgrade

### ISSUE THREAD

**Issue by kujeger** [tulir/mautrix-facebook#123]
Specifically, it does not handle `@` in the password.

My connection string is `postgres://someuser:pass@word@hostname/database` 

After upgrading, I get errors like this in the logs:
`socket.gaierror: [Errno -2] Name does not resolve`

If I change the string to (the incorrect password) `postgres://someuser:password@hostname/database` 
It successfully connects and then correctly errors with an incorrect password.

**Comment by Moto-John** [comment]
I had the same problem even on versions before 0.2. I guess changing your database password to something without @ is a good temporary solution

**Comment by kujeger** [comment]
Yeah, I changed the password to avoid the issue

**Comment by tulir** [comment]
Looks like asyncpg requires that you percent-encode special characters: MagicStack/asyncpg#472
