### ISSUE TITLE
Is alembic still needed?

### ISSUE THREAD

**Issue by baltitenger** [tulir/mautrix-facebook#134]
I don't see any use of `alembic.ini` or `alembic/`, yet they are present in the repository and `setup.py` installs them. If they are indeed redundant, could you remove them from `setup.py`? If they are needed, they should be moved to `/usr/share/mautrix-facebook`, they shouldn't be just lying around in `/usr`.

**Comment by tulir** [comment]
They're used by alembic. Alembic is no longer used for database upgrades, but old installations still have to upgrade to the latest revision before switching over to the new system. I'll probably remove it after releasing v0.2.0.

The setup instructions require a virtualenv for a reason. `example-config.yaml` isn't going away even after alembic is removed.
