### ISSUE TITLE
Some DMs show up as rooms

### ISSUE THREAD

**Issue by tlaundal** [tulir/mautrix-facebook#136]
Not sure if this is an issue of Element or this bridge, but here goes:

Some "direct messages" on Facebook messenger show up under "People" in Element, while others show up under "Rooms".
I would expect all direct messages to show under "People", and all messenger "groups" to show under "Rooms".

If I try to start a chat with a messenger user who is already listed under "Rooms", the puppet immediately leaves the new chat with the message: "You already have a private chat with me: <Link to existing room>".

**Comment by tulir** [comment]
It's a bug in how DMs are classified in Matrix, https://github.com/tulir/mautrix-facebook/blob/master/mautrix_facebook/example-config.yaml#L116-L119 can be used to work around it

**Comment by tlaundal** [comment]
> It's a bug in how DMs are classified in Matrix, https://github.com/tulir/mautrix-facebook/blob/master/mautrix_facebook/example-config.yaml#L116-L119 can be used to work around it

Thanks. Perhaps mention this somewhere in the documentation as well?
Though I should of course have checked the config file :)

**Comment by hwittenborn** [comment]
I've noticed some of my chats on Messenger itself can end up being just two-person groups if it's set up a certain way(don't know how, just noticing it). Maybe that's what you're seeing?

I'd look at the people on Synapse and see if you're Facebook avatar is being created as a separate user in it(Synapse user, your FB user, then other users) - if it is, I'm pretty sure it's just a group on Messenger itself.
