### ISSUE TITLE
Workplace support

### ISSUE THREAD

**Issue by homebeach** [tulir/mautrix-facebook#14]
Add support for [Facebook workplace](https://www.facebook.com/workplace). According to [developer documentation](https://developers.facebook.com/docs/workplace/), there are several [APIs](https://developers.facebook.com/docs/workplace/reference). There seems to be [support for bots](https://developers.facebook.com/docs/workplace/bots) too. Here is corresponding issue in matrix wishlist: https://github.com/turt2live/matrix-wishlist/issues/269.

**Comment by tulir** [comment]
That would probably be a separate bridge
