### ISSUE TITLE
container fails to start with matrix-docker-ansible-deploy

### ISSUE THREAD

**Issue by treethought** [tulir/mautrix-facebook#140]
This is probably related to the recent removal of alembic, but I am unable to start mautrix-facebook by enabling it in the matrix-docker-ansible-deploy playbook.

```
 Unable to start service matrix-mautrix-facebook.service: Job for matrix-mautrix-facebook.service failed because the control process exited with error code.
    See "systemctl status matrix-mautrix-facebook.service" and "journalctl -xe" for details.
```

journalctl -xe
```
synapse matrix-mautrix-facebook[30822]: docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "alembic": executable file not found in $PATH: unknown.

```

**Comment by tulir** [comment]
Not related to the bridge and already fixed in the playbook

**Comment by bmanturner** [comment]
@tulir What is the fix? I just started experiencing this yesterday.

**Comment by bmanturner** [comment]
The fix is to update the ansible playbook. https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/fef6d5762642777778fc630bf6590755140e21c1
