### ISSUE TITLE
issue with the web-based login authentification

### ISSUE THREAD

**Issue by hafx** [tulir/mautrix-facebook#156]
Hi, 
I would like to use the web-based login (new in version 0.2.1) 
(https://docs.mau.fi/bridges/python/facebook/authentication.html)

What am I supposed to use as external base URL ?
Is it facebook.com ?
https://github.com/tulir/mautrix-facebook/blob/9363c4541785a45e69b2f73d0bc5057ecb177619/mautrix_facebook/example-config.yaml#L36-L50  

Thanks

**Comment by woojoo666** [comment]
@hafx did you figure this out? I'm running into the same issue
