### ISSUE TITLE
Messages stop being fetched until 'refresh' command is sent

### ISSUE THREAD

**Issue by HammyHavoc** [tulir/mautrix-facebook#167]
Seems that every few hours each bridge user needs to send a 'refresh' command.

**Comment by HammyHavoc** [comment]
Found the solution: https://github.com/tulir/mautrix-facebook/issues/45#issuecomment-763045511

Though this should probably set by default. I've set it to 3600 for the time being (hourly).

**Comment by JuniorJPDJ** [comment]
Yup, setting it to some sane value by default would be cool

**Comment by HammyHavoc** [comment]
Just for clarification, would you say that 3600 is within the realms of sanity? :- )

**Comment by JuniorJPDJ** [comment]
I'm using 43200 and had no problems to this day.
