### ISSUE TITLE
Messages from facebook sent before room opened in Matrix not visible

### ISSUE THREAD

**Issue by vranki** [tulir/mautrix-facebook#24]
0. Setup bridge
1. Someone messages you on facebook
2. A bridge invites you to new room
3. Accept invite
4. See that other user has joined on the room but there are no messages in the room.

Workaround: open facebook and read the message, then reply via Matrix. 
After that messages work fine but the messages sent before joining the room are missing.

**Comment by olmari** [comment]
..On Mautrix-facebook version https://github.com/tulir/mautrix-facebook/commit/e0580690ab76df84e916282e987160fe63c2e45a

**Comment by DoM1niC** [comment]
I have a other Problem since some Days I could send Messages but if someone send from Fb to Matrix nothing appear in Matrix only sending is working the Chat was already working in the past for me without any changes on Matrix Bridge .... :(

**Comment by tulir** [comment]
@DoM1niC that's an unrelated issue that's fixed on the `update-fbchat` branch

**Comment by DoM1niC** [comment]
> @DoM1niC that's an unrelated issue caused by facebook breaking stuff that's fixed on the `update-fbchat` branch

Yep is live now on Master but I was looking for some days without any progress about this but THX to fix the issue <3

**Comment by tulir** [comment]
This was a pre-backfilling issue, so probably fixed by now
