### ISSUE TITLE
Ghost users has always offline status.

### ISSUE THREAD

**Issue by bwskin** [tulir/mautrix-facebook#251]
My imported facebook friends shows always as offline. Sometimes when user is connected it show `Offline for 0s`

client: Element Desktop / Element Android

**Comment by tulir** [comment]
Presence is very low priority (mostly because the Matrix/Element devs don't care about it either), so bugs related to it probably won't be fixed.

Did you turn on the config option? https://github.com/mautrix/facebook/blob/v0.4.0/mautrix_facebook/example-config.yaml#L155-L157

**Comment by bwskin** [comment]
> Did you turn on the config option? https://github.com/mautrix/facebook/blob/v0.4.0/mautrix_facebook/example-config.yaml#L155-L157

Yes, i have this option turned on.

**Comment by mrdev023** [comment]
Same for me for all contacts
