### ISSUE TITLE
Inability to login again when already logged in

### ISSUE THREAD

**Issue by spantaleev** [tulir/mautrix-facebook#30]
If you're already logged in, sending a new `login <email> <password>` command would fail with a "Something went wrong" HTML response coming from Facebook.

I'm not sure if this always happens or if it happens only in certain more weird cases (after a password change, 2FA-enabling, etc.), but I could get it to consistently happen to me.

In my case, I had recently enabled 2FA and decided it'd be best if I create a new login session for the bridge, go through the 2FA verification, etc. I found out that all my login attempts would result in an error (`Login failed. Check email/password. (Failed on url: https://m.facebook.com/login.php?login_attempt=1)`) -- not very helpful. Upon further debugging, I found out that Facebook replies with HTML that says "Something went wrong". Still not too helpful to figure out what's wrong.

I thought [fbchat-asyncio](https://github.com/tulir/fbchat-asyncio) is lagging behind the original [fbchat](https://github.com/carpedm20/fbchat) library and has some bug with handling 2FA or [verifying that it lands on the homepage](https://github.com/carpedm20/fbchat/commit/efc8776e709c960d27598a8443d4d479425c6984), but.. after testing both libraries in a clean environment, I've confirmed that both can successfully complete a 2FA login for my account.

Running this code in the (failing) bridge's container **resulted in a successful login**:

```python
from fbchat import Client
from fbchat.models import *
client = Client()

import asyncio

async def work():
        print(repr(await client.login('EMAIL_ADDRESS', 'PASSWORD')))
        if not await client.isLoggedIn():
                print('Not logged in')
        else:
                print('Logged in')

loop = asyncio.get_event_loop()
loop.run_until_complete(work())
loop.close()
```

This lead me to believe that the library is fine, and it's the `Client` object used by the bridge that is somehow contaminated. Having not dug into the bridge's code too much, I'm only guessing but.. I suppose there's a single `Client` object associated with my Matrix user id. Given that the bridge is currently doing work for me, this `Client` object's session's cookie jar contains some stuff from my existing login session. Trying to do a fresh `login()` makes all those old cookies get sent and Facebook doesn't like that for some reason.

I've worked around this by patching [fbchat-asyncio](https://github.com/tulir/fbchat-asyncio)'s `_client.py` file, so that `_login()` would do `self._resetValues()` first.

This allowed me to replace my existing login session with a new one successfully.

I'm not sending a patch to fbchat-asyncio, as I'm not sure if this is the proper way to solve it. Perhaps resetting values midway can cause other stuff to break.. Perhaps there's a better way for the bridge to gracefully replace an old `Client` with a new one?

**Comment by tulir** [comment]
Logout probably works in the new system, open a new issue if not
