### ISSUE TITLE
Facebook constantly detects "suspicious activity"

### ISSUE THREAD

**Issue by BrechtSerckx** [tulir/mautrix-facebook#32]
Facebook very often flags the appservice as "suspicious activity" and prompts to change my password (without option to skip this). I've hade to change my password more than 20 times in the last few months. Is there some way to avoid this?

**Comment by tulir** [comment]
Try enabling 2-factor auth and using the second part of the logging in section in https://github.com/tulir/mautrix-facebook/wiki/Authentication

**Comment by BrechtSerckx** [comment]
I'll try it out, thank you.

**Comment by ingochris** [comment]
> I'll try it out, thank you.

@BrechtSerckx: Have you had the chance to test this, and did it solve the issue?

**Comment by BrechtSerckx** [comment]
I haven't had any problems since, so for now I would say that the issue is solved.
