### ISSUE TITLE
DB creation fail : parser bug

### ISSUE THREAD

**Issue by Pcornat** [tulir/mautrix-facebook#35]
Hello,

When I do this `alembic upgrade head` it crashes because of the password I have for my postgres DB. In my password there is the `/` character… And so it crashes when it is reading this line.

If you need to know something else, tell me and I will give you the information you need.

Thank you in advance and sorry for my bad English (not native).

**Comment by tulir** [comment]
Are you sure it's about `/` and not `%`?
