### ISSUE TITLE
Thumbs up on Riot Web doesn't translate into thumbsup on Messenger

### ISSUE THREAD

**Issue by pot8to** [tulir/mautrix-facebook#37]
When reacting with the :+1: on Riot Web (1.5.5), Riot sends the following event:

```
{
    "type": "m.reaction",
    "sender": "@kevin:kliu.io",
    "content": {
        "m.relates_to": {
            "rel_type": "m.annotation",
            "event_id": "$aIiBcFJwYn9mcXLUhR1M8HsjjBPQ9zdeKFX51CbNWFk",
            "key": "👍️"
        }
    },
    "event_id": "$Hi0PLHhOueAom2zjmbWh3V1XW-FwxmpDptQeGtWk2uo",
    "origin_server_ts": 1575218667406,
    "unsigned": {
        "age": 95809,
        "transaction_id": "m1575218667318.25"
    },
    "room_id": "!ZzJhvgtimjgTccAAKf:kliu.io"
}
```

Where the :+1: is actually `👍<fe0f>`; that is, the :+1: followed by a Unicode variation selector. This appears to be mentioned in https://github.com/vector-im/riot-web/issues/9785. The facebook bridge appears to only map a plain :+1:: https://github.com/tulir/mautrix-facebook/blob/2de54e1b48a110052e9be1073105f6ef301e5397/mautrix_facebook/portal.py#L426. Thus, the reaction is not applied on the Facebook side.

Sending from other clients (e.g. RiotX) doesn't appear to have this issue, likely because RiotX just sends a plain :+1:.

**Comment by tulir** [comment]
Are you sure you're using Riot 1.5.5? This was fixed like 3 weeks ago.

**Comment by pot8to** [comment]
Ah, good to know. Looks like it works on /develop for me as well - probably was using an older Riot version without knowing it.
