### ISSUE TITLE
Problem with registration

### ISSUE THREAD

**Issue by Pcornat** [tulir/mautrix-facebook#39]
I followed the wiki, correctly.

The command to generate the registration `python -m mautrix_facebook -g` give me this :
`[2019-12-01 21:37:25,877] [CRITICAL@mau.init] Configuration error: appservice.as_token not configured. Did you forget to generate the registration?`

So, unless you make a real tutorial with the possible mistakes, etc, issues are going to be the only way to have our problems solved.

Thank you in advance.

PS : and concerning the issue with DB and parser, no I do not use a `%` character in my password, so it IS the `/` that making the problem (now I can not check as I changed the OS of my Raspberry Pi).

**Comment by tulir** [comment]
Fixed in mautrix-python 0.4.0rc3
