### ISSUE TITLE
Reply bridging

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-facebook#4]

**Comment by mrjohnson22** [comment]
Note that [the roadmap](https://github.com/tulir/mautrix-facebook/blob/master/ROADMAP.md) says Matrix->FB reply bridging works, but it actually doesn't.

**Comment by tulir** [comment]
Seems to work fine in both directions, other than unrelated bugs affecting all message delivery

**Comment by mrjohnson22** [comment]
Actually, the message I replied to was one made by a Matrix user not signed in to Facebook. That scenario is out-of-scope entirely. In fact, I'm impressed the bridge didn't crash...!
