### ISSUE TITLE
Changing displayname_preference back to "name" doesn't update names

### ISSUE THREAD

**Issue by aristaeus** [tulir/mautrix-facebook#41]
Steps to reproduce:

1. Set `displayname_preference` to something else
2. Set it back to `name`

The bug seems to be at `mautrix_facebook/puppet.py:170`

```python
    async def _update_name(self, info: FBUser) -> bool:
        name = self._get_displayname(info)
        if name != self.name:
```

From a glance at the code it's not clear whether `self.name` is being loaded from the database or from Facebook, but either way it is always the "Full Name". This means the code doesn't enter the if statement, as `name` is always the same as the new display name.

**Comment by NicolaiSoeborg** [comment]
If you restart the bridge and/or do a `sync --contacts` then names will be updated based on `displayname_preference`

**Comment by tulir** [comment]
`UPDATE puppet SET name_set=false;` in the database can be used to tell the bridge to re-send all names to the homeserver.
