### ISSUE TITLE
Feedback for when a message isn't bridged

### ISSUE THREAD

**Issue by mrjohnson22** [tulir/mautrix-facebook#43]
There currently isn't a way to tell if a message sent in a portal room failed to be bridged, other than logging into another Messenger client or waiting to get a read receipt from a Facebook user (which won't ever happen if your message wasn't bridged). It would be very helpful if there was some kind of warning for when a message failed to be bridged. (This just bit me and it is very embarrassing!)

One idea is to have the Facebook bot user post a read receipt for successfully-bridged messages (like matrix-appservice-discord does), but that isn't an option for 1:1 chat portals which the Facebook bot user is not a member of. The next best thing would be to have the puppet for the non-logged in Facebook user in a 1:1 portal posting a message that is clearly a "failed to bridge" warning message from the appservice and not a message sent from the actual human Facebook user.

**Comment by tulir** [comment]
This is done now
