### ISSUE TITLE
Bridge starting messages

### ISSUE THREAD

**Issue by JorikSchellekens** [tulir/mautrix-facebook#46]
Would be nice to have 'bridge starting' and 'bridge ready' messages from the bot.

**Comment by emorrp1** [comment]
Yeah, I was watching the logs, but that's only feasible for the bridge admin. The thing that took the longest was creating an account for all facebook friends, so some progress like "Initialised X of Y facebook friends" every 50 or so would be good.

**Comment by tulir** [comment]
The "Connected to Facebook Messenger" message now more or less does this
