### ISSUE TITLE
Add dependency on python3-dev

### ISSUE THREAD

**Issue by emorrp1** [tulir/mautrix-facebook#47]
Following the [setup instructions](https://github.com/tulir/mautrix-facebook/wiki/Bridge-setup) on Debian buster (raspberry pi), I was unable to get past the pip install step for 0.1.0.dev16. Relevant "yarl" log entries below, same for "ruamel.yaml.clib". `sudo apt install python3-dev` resolved it.

```
  Building wheel for yarl (setup.py) ... error
   command: /usr/local/src/mautrix-facebook/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fhzbml9i/yarl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fhzbml9i/yarl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7ocn2b2s

  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -I/usr/local/src/mautrix-facebook/include/python3.7m -c yarl/_quoting.c -o build/temp.linux-armv7l-3.7/yarl/_quoting.o
  yarl/_quoting.c:4:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for yarl
```

**Comment by tulir** [comment]
What do you mean by add dependency?

**Comment by bobpaul** [comment]
@emorrp1 To add a Debian specific package as a dependency, someone would have to package it for Debian. 

For example, I maintain a package for this project on Archlinux (AUR) and I had to add a bunch of package dependencies to _my package_. I wouldn't expect upstream to be responsible for idiosyncrasies across all of the different Linux distros. That's my job as a package maintainer.

For easy installation on any distro, use the `Dockerfile`.
