### ISSUE TITLE
fb bridge mixing up encryption keys when new device is added

### ISSUE THREAD

**Issue by ericmigi** [tulir/mautrix-facebook#52]
1 logged onto novaweb in browser A send/receive FB messages fine
2 log onto novaweb in browser session B, do not add to key backup because it's a brief testing session
3 open novaweb A again, receive this message when sending/receiving FB messages

![image](https://user-images.githubusercontent.com/1048265/80407203-1ea8fb80-887a-11ea-8587-af74cf989e35.png)

**Comment by tulir** [comment]
This should work better now that it doesn't use matrix-nio anymore
