### ISSUE TITLE
Packaging mautrix-facebook using stdeb fails in Debian

### ISSUE THREAD

**Issue by joelpet** [tulir/mautrix-facebook#53]
### Steps to reproduce (using Docker)

1. docker run --rm -it --workdir /tmp debian:buster
2. apt-get update && apt-get install -y python-stdeb python3-stdeb
3. pypi-download mautrix-facebook
4. tar -xf mautrix-facebook-0.1.0.dev16.tar.gz
5. cd mautrix-facebook-0.1.0.dev16
6. python3 setup.py --command-packages=stdeb.command bdist_deb

### Expected result

Successful build of .deb packages.

### Actual result

```
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    with open("requirements.txt") as reqs:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

--- 

I notice that the tarball downloaded in step 3 does not contain the `requirements.txt` file. Would it be possible and make sense to have it included in the tarball found on [PyPI](https://pypi.org/project/mautrix-facebook)?

**Comment by tulir** [comment]
Should be included now
