### ISSUE TITLE
FB->MX mentions not converted

### ISSUE THREAD

**Issue by amalon** [tulir/mautrix-facebook#61]
Facebook mentions don't seem to be converting to matrix links on latest master (commit d6157c8421cb). The body of the matrix message shows just "@<name>" and the formatted_body shows "@<number><name>" (maybe there are other characters that can't be printed).

Perhaps the regex at https://github.com/tulir/mautrix-facebook/blob/master/mautrix_facebook/formatter/from_facebook.py#L30
needs updating or something?

**Comment by tulir** [comment]
Oh yeah, that has always been wrong
