### ISSUE TITLE
Tried to parse UnavailableMessagingActor as a user.                                                                                                                         

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-facebook#74]
I'm getting warning like this, but `UnavailableMessagingActor` is actually an user but with banned/deleted FB account.
It probably means bridge will not be able to copy messages created by this user (am I right?) which is not the best behavior to get.

```
mautrix-facebook_1  | [2020-06-12 09:08:24,126] [WARNING@fbchat] Tried to parse UnavailableMessagingActor as a user.                                  
```

Example data from biiiiig debug returned in log:
```
{'messaging_actor': {'id': '100010685650091',
  '__typename': 'UnavailableMessagingActor',
  'name': 'Użytkownik Facebooka',
  'url': None,
  'big_image_src': {'uri': 'https://scontent-waw1-1.xx.fbcdn.net/v/t1.30497-1/cp0/c15.0.50.50a/p50x50/84628273_176159830277856_972693363922829312_n.jpg?_nc_cat=1&_nc_sid=12b3be&_nc_oc=AQmawmxOlB3H_7gDEqh-qVMKZxCElDIGxRkoQjP3GjC0BNHqOCnF47eFO24nYOhAAPk&_nc_ht=scontentwaw1-1.xx&oh=ed5004320267aeabce371b6fb0c739e2&oe=5F0A9138'},
  'is_message_blocked_by_viewer': False}}
```
Where `'Użytkownik Facebooka'` means `'Facebook user'` in english.

**Comment by Legogris** [comment]
My log is also *filled* with these, interspersed with `Tried to parse Page as a user.`. I htink this may be a regression as I didn't see this from a previous version from 2020-08.

**Comment by tulir** [comment]
This no longer applies, open a new issue with new logs if there are similar issues
