### ISSUE TITLE
Own puppet gets invited to room even if not needed

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-facebook#75]
Own puppet is getting invited into chat in sync process (bridge restart or sync command) even if no action is needed nor taken.
It makes chats very much spammed after sync or bridge restart.
This probably should be the case only if messages are going to be sent to matrix.

Example:
![Screenshot_20200612-151306_Trebuchet](https://user-images.githubusercontent.com/7334549/84506250-5d2a3680-acbf-11ea-9b8f-4365705c9db4.png)

**Comment by JuniorJPDJ** [comment]
Any progress?
It's veryyyy annoying ;X
![Screenshot_20200808_132052](https://user-images.githubusercontent.com/7334549/89708797-90fda180-d97a-11ea-8761-6cc92db75f19.png)

**Comment by Cerothen** [comment]
I too have this issue, I have my bridges restart once per day and any Facebook rooms I have get this when the bridge restarts.

**Comment by waclaw66** [comment]
@tulir: The isssue still persists. Is there any option how to disable to get invited to not initiated rooms/contacts? When mautrix-facebook is restarted I get always a bunch of invitations.

**Comment by tulir** [comment]
That doesn't sound like this issue

**Comment by waclaw66** [comment]
You're right, I have spammed the invitation list after each restart, not content of chats. Question is, is that normal behaviour?
> 
> That doesn't sound like this issue
