### ISSUE TITLE
Bridge seen as "Unknown", constantly getting blocked

### ISSUE THREAD

**Issue by Scorcerer** [tulir/mautrix-facebook#76]
Hi!
My facebook bridge is constantly getting disconnected, and after a couple of retries facebook sees it as malicious login tries and blocks it out. Then I login to FB, and it asks me to generate new password, review recent changes, stuff like that. Probably my VPS on which i have my matrix server and all bridges being in different city don't help here, but there should be a way to make FB recognize this as proper way of logging in. As i have 2FA enabled (it was even worse without it), and both login and login-cookie give me the same results, I started wondering if there's a any way to fix this?
Generating separate passwords don't work (i don't think those can be used for messenger connections form non-whitelisted apps.

**Comment by bobpaul** [comment]
>  but there should be a way to make FB recognize this as proper way of logging in. 

This might not be a true statement. I'm really interested as well, as I've been struggling with this, too, and even had my Oracle Cloud account terminated after Facebook did one of their account lockouts (I assume there's an automated way to contact some of the larger VPS providers like Oracle).

I wouldn't be surprised if Facebook has a list of IP address ranges used by common VPS providers and watches for things that look like robots. A puppeting bridge probably looks a lot like a robot.

**Comment by Scorcerer** [comment]
I don't think it's a problem of IP white/grey/blacklisting on FB side - I'm using a small provider in not so usual country.
What's most interesting for me is that FB sees bridge as 'unknown browser' and therefore each time it tries to connect it's seen as new browser, which needs confirmation and therefore is suspicious. I thought for some bridges there was a way to set user-agent - maybe it'd be enough to set it somehow?

**Comment by mmilata** [comment]
Same here & I'm running out of passwords since FB won't let me use the old one after blocking:D

FWIW [purple-facebook](https://github.com/dequis/purple-facebook) seems to avoid this issue somehow.

**Comment by auscompgeek** [comment]
> FWIW [purple-facebook](https://github.com/dequis/purple-facebook) seems to avoid this issue somehow.

purple-facebook pretends to be the Facebook Messenger mobile app rather than a web browser. This seems to be the more sensible approach to me.

**Comment by tulir** [comment]
I re-added the user agent setting (it was removed when I updated to a newer version of the library). Other than that, there's not much I can do if facebook doesn't like the bridge

**Comment by vlabo** [comment]
I had the same issue. 
It's kind of strange but when I started running synapse and mautrix-facebook bridge as root user the facebook stopped blocking my account
