### ISSUE TITLE
sample systemd virtualenv service

### ISSUE THREAD

**Issue by emorrp1** [tulir/mautrix-facebook#81]
As there isn't one on the wiki, here's a suggested `mautrix-facebook.service` file where the user's home is `/usr/local/src/mautrix-facebook`.

```
[Unit]
Description=Matrix-Facebook bridge

[Service]
WorkingDirectory=~
ExecStart=/usr/local/src/mautrix-facebook/bin/python -m mautrix_facebook
User=mautrix-facebook

[Install]
WantedBy=multi-user.target
```

**Comment by tulir** [comment]
Feel free to add it to the wiki, probably a new page in the setup section
