### ISSUE TITLE
FB user gets invited, joins and leaves the room every two minutes

### ISSUE THREAD

**Issue by jeena** [tulir/mautrix-facebook#83]
I'm having those messages in the room where I try to chat with my brother who is on Facebook:

```
00:02 Karlo Sono V. Dach (FB) invited Jeena Pa (FB).
00:02 Jeena Pa (FB) joined the room.
00:02 @facebook_728407677:jeena.net left the room.
```

And on the timestamp I see that this is happening every other minute, so now I have hudreds of those messages in there and I don't really understand what is happening here. Why does my brothers account invite my account in here on matrix? My normal matrix user is already here.

![fb](https://user-images.githubusercontent.com/151764/87774589-03201200-c825-11ea-9c14-137f1c2ad015.png)

**Comment by tulir** [comment]
Did you configure the bridge to auto-reconnect every 2 minutes or something? The issue is #75, but it really shouldn't happen that often

**Comment by jeena** [comment]
No not really, and it happens mostly with one fb user, the other ones seem to do what #75 describes.
