### ISSUE TITLE
Force sync of profile photos

### ISSUE THREAD

**Issue by seanfarley** [tulir/mautrix-facebook#86]
It seems that bigger profile photos are now being used after 152872edf54c132735499ccef6aee3170c9121b0, yay! Is there anyone to force a refresh of all the photos / avatars / thumbnails?

**Comment by seanfarley** [comment]
I should have also mentioned that I've tried running `sync` and rebooting the services.

**Comment by NicolaiSoeborg** [comment]
If `update_avatar_initial_sync` is set to `true` and you run `sync --contacts` then [it will update avatars](https://github.com/tulir/mautrix-facebook/blob/7190715a61ef1ad328b04c050a4263936a1bebad/mautrix_facebook/user.py#L405-L408) :smile:

**Comment by seanfarley** [comment]
Ah, nice; thanks very much :-)

Unfortunately (and completely unrelated), running the matrix bridge from my vps is damn near impossible because FB keeps flagging it as suspicious :-(

Either way, I appreciate the explanation
