### ISSUE TITLE
Can not generate registration file: homeserver.address not configured

### ISSUE THREAD

**Issue by Legogris** [tulir/mautrix-facebook#88]
When using the docker container (built from current master #d6b78ea40a32abdd44e75b50d036d4977692e603) configuration generation works fine but registration fails:

```
$ docker run --rm -v `pwd`:/data:z my-mautrix-facebook:latest
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2020-07-27 09:36:16,158] [CRITICAL@mau.init] Configuration error: homeserver.address not configured
Didn't find a registration file.
Generated one for you.
Copy that over to synapses app service directory.
```

**Comment by Legogris** [comment]
Might be coincidental, but it worked fine when rerunning with mautrix `0.7.0b4`

**Comment by tulir** [comment]
The error is saying you didn't edit your config after generating it. It shouldn't work with any version

**Comment by Legogris** [comment]
I was actually serving from `example.com` without TLS during the testing phase, so that explains it :sweat_smile:
