### ISSUE TITLE
MQTT disconnected until manual sync

### ISSUE THREAD

**Issue by mrjohnson22** [tulir/mautrix-facebook#96]
Upon bridge startup, the MQTT listener is disconnected until a `sync` command is called manually.

It also appears that the MQTT connection state isn't properly tracked:

![mautrix-facebook-connection](https://user-images.githubusercontent.com/8988672/92989890-96806700-f4a5-11ea-9e90-d40262021df6.png)

It used to be (about a week or two ago) that the bridge would automatically connect the MQTT listener on startup, but that no longer happens.

**Comment by mrjohnson22** [comment]
It's true that turning on auto-syncing (with `initial_chat_sync` in the config) would solve this, but I don't want to have auto-syncing on.

I don't want it because there is an odd edge case where if two double-puppetted Matrix users who are logged into the same FB account are present in the same portal room, an auto-sync will cause at least one of those users to always re-post the most recent message they sent. This affects https://github.com/mrjohnson22/matrix-imposter-bot, but probably no other use-case.

**Comment by tulir** [comment]
This is expected until I (or someone else) get around to making the bridge do the chat list API request even when `initial_chat_sync` is 0.
