### ISSUE TITLE
Bridge is not logging in with `community_template` option set

### ISSUE THREAD

**Issue by wvffle** [tulir/mautrix-facebook#97]
The problem I'm experiencing is that when I set `community_template` to the suggested value, bridge is starting fine though there's no message that it's connected to the facebook messenger. None of the bridged channels work. 

The problem is due to `enable_group_creation` being disabled in the synapse configuration. In such case the bridge should at least inform that it's unable to create new community

**Comment by tulir** [comment]
Config comment was improved in #105
